[[main]]
identifier = 'news'
name = 'News'
url = 'en/news/'
weight = 10

[[main]]
identifier = 'classes'
name = 'Classes'
url = 'en/classes/'
weight = 20

[[main]]
identifier = 'events'
name = 'Events'
url = 'en/events/'
weight = 30

[[main]]
name = "Minor Swing Social"
url = "en/minor-swing-social/"
parent = "events"
weight = 31

#[[main]]
#name = "Friday Night Balboa"
#url = "en/friday-night-balboa/"
#parent = "events"
#weight = 32
#
#[[main]]
#name = "Mattstedt"
#url = "en/mattstedt/"
#parent = "events"
#weight = 33
#
#[[main]]
#name = "Open Doors Day"
#url = "en/open-doors-day/"
#parent = "events"
#weight = 34
#
#[[main]]
#name = "Swing Tea Time"
#url = "en/swing-tea-time/"
#parent = "events"
#weight = 35

#[[main]]
#name = "Swing Brunch"
#url = "en/swing-brunch/"
#parent = "events"
#weight = 35

#[[main]]
#identifier = 'calloway'
#name = 'Studio'
#url = 'en/calloway/'
#weight = 40

#[[main]]
#parent = 'calloway'
#name = 'Renting'
#url = 'en/renting/'
#weight = 41

[[main]]
identifier = 'association'
name = 'Our association'
url = 'en/association/'
weight = 50

#[[main]]
#parent = 'association'
#identifier = 'membership'
#name = 'Membership'
#url = 'en/membership/'
#weight = 51

#[[main]]
#parent = 'association'
#identifier = 'history'
#name = 'History'
#url = 'en/history/'
#weight = 52

[[main]]
identifier = 'contact'
name = 'Contact & Imprint'
url = 'en/contact/'
weight = 60

[[main]]
weight = 70
identifier = "facebook"
pre = "<i class='fab fa-facebook fa-fw' aria-hidden='true'></i>"
post = ""
name = ""
url = "https://www.facebook.com/groups/swingconnection.leipzig"
title = "Facebook"

[[main]]
weight = 80
identifier = "instagram"
pre = "<i class='fab fa-instagram fa-fw' aria-hidden='true'></i>"
post = ""
name = ""
url = "https://www.instagram.com/swingconnectionleipzig/"
title = "Instagram"

[[main]]
weight = 90
identifier = "youtube"
pre = "<i class='fab fa-youtube fa-fw' aria-hidden='true'></i>"
post = ""
name = ""
url = "https://www.youtube.com/user/swingconnection"
title = "Youtube"	
