[[main]]
identifier = 'aktuelles'
name = 'Aktuelles'
url = '/aktuelles/'
weight = 10

[[main]]
identifier = 'tanzkurse'
name = 'Tanzkurse'
url = '/tanzkurse/'
weight = 20

[[main]]
name = 'Sommerprogramm'
url = '/sommerprogramm/'
parent = "tanzkurse"
weight = 21

[[main]]
identifier = 'veranstaltungen'
name = 'Veranstaltungen'
url = '/veranstaltungen/'
weight = 30

[[main]]
name = "Minor Swing Social"
url = "/minor-swing-social/"
parent = "veranstaltungen"
weight = 31

[[main]]
name = "Friday Night Balboa"
url = "/friday-night-balboa/"
parent = "veranstaltungen"
weight = 32

#[[main]]
#name = "Mattstedt"
#url = "/mattstedt/"
#parent = "veranstaltungen"
#weight = 33

[[main]]
name = "Tag der offenen TÃ¼r"
url = "/tag-der-offenen-tuer/"
parent = "veranstaltungen"
weight = 34

[[main]]
name = "Swing Tea Time"
url = "/swing-tea-time/"
parent = "veranstaltungen"
weight = 35

#[[main]]
#name = "Swing Brunch"
#url = "/swing-brunch/"
#parent = "veranstaltungen"
#weight = 35

[[main]]
identifier = 'calloway'
name = 'Tanzstudio'
url = '/calloway/'
weight = 40

[[main]]
parent = 'calloway'
name = 'Einmietung'
url = '/einmietung/'
weight = 41

[[main]]
identifier = 'verein'
name = 'Unser Verein'
url = '/verein/'
weight = 50

[[main]]
parent = 'verein'
identifier = 'mitgliedschaft'
name = 'Mitgliedschaft'
url = '/mitgliedschaft/'
weight = 51

[[main]]
parent = 'verein'
identifier = 'geschichte'
name = 'Vereinsgeschichte'
url = '/geschichte/'
weight = 52

[[main]]
identifier = 'kontakt'
name = 'Kontakt & Impressum'
url = '/kontakt/'
weight = 60

[[main]]
weight = 70
identifier = "facebook"
pre = "<i class='fab fa-facebook fa-fw' aria-hidden='true'></i>"
post = ""
name = ""
url = "https://www.facebook.com/groups/swingconnection.leipzig"
title = "Facebook"

[[main]]
weight = 80
identifier = "instagram"
pre = "<i class='fab fa-instagram fa-fw' aria-hidden='true'></i>"
post = ""
name = ""
url = "https://www.instagram.com/swingconnectionleipzig/"
title = "Instagram"

[[main]]
weight = 90
identifier = "youtube"
pre = "<i class='fab fa-youtube fa-fw' aria-hidden='true'></i>"
post = ""
name = ""
url = "https://www.youtube.com/user/swingconnection"
title = "Youtube"
